version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.12.0
    container_name: selenium-hub
    ports:
      - "4444:4444" # Expose Selenium Grid Hub
    environment:
      - SE_GRID_MAX_SESSION=5
      - SE_GRID_NEW_SESSION_WAIT_TIMEOUT=300

  chrome:
    image: selenium/node-chrome:4.12.0
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm # Share memory to prevent Chrome crashes
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox:4.12.0
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
